### ISSUE TITLE
API status returning success:false

### ISSUE THREAD

**Issue by RfadnjdExt** [KatowProject/Kusonime-API#2]
The Kusonime-API is currently returning {"success":false} for all API requests. This issue started occurring on May 27, 2023. The affected API endpoint is /.

Error message: When making a request to the API, the following error message is returned:
```
{"success":false}
```
Steps to reproduce:

Make a GET request to the /.
Check the response for the error message mentioned above.
Expected behavior: The API should return a successful response with the requested data.

Additional information:

This issue is affecting all API requests, not just specific ones.
The issue is not related to any changes made on the client-side.
Please let me know if you need any further information to resolve this issue. Thank you.

**Comment by KatowProject** [comment]
fixed
